# Generated by Django 3.1.2 on 2020-10-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='singer',
            field=models.CharField(default='unknown singer', max_length=100),
        ),
    ]
