# Generated by Django 3.1.2 on 2020-10-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20201002_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio',
        ),
        migrations.AddField(
            model_name='song',
            name='sid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
