# Generated by Django 3.1.2 on 2020-10-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20201002_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='url',
            field=models.URLField(default='default url'),
            preserve_default=False,
        ),
    ]
