# Generated by Django 3.1.2 on 2020-10-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_song_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(default='1', upload_to=''),
            preserve_default=False,
        ),
    ]
