# Generated by Django 3.1.2 on 2020-10-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20201004_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(upload_to=''),
        ),
    ]
