# Generated by Django 3.1.2 on 2020-10-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_leaderboard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeaderBoard',
            new_name='Leader',
        ),
    ]
